### ISSUE TITLE
Installation intruction

### ISSUE THREAD

**Issue by kvvaradha** [emredurukn/betcalsa#1]
Hello dude, 

You have done a great job with  document scanning.  And i wanted to try this for mine. 

Can you provide installation instruction ?

Will it work on new version of xcode and ios 14.1 ?

**Comment by emredurukn** [comment]
Hi,

It should work when you install the necessary pods and build the project in xcode. I will try and update readme as soon as I am available.

**Comment by emredurukn** [comment]
Sorry mate I tried the swift 5 conversion on xcode but got syntax error. It's been a long time since I messed with Swift. If you want to make the project swift 5 compatible, you can fork it.
